name: Add new release
run-name: ${{ github.actor }} is creating a new release
on:
  push:
    branches:
      - actions
    paths:
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: install dependencies
        run: |
          npm install

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install vsce
        run: |
          npm install -g vsce

      - name: Package extension
        run: |
          vsce package

      - name: Create GitHub release
        run: |
          TAG_NAME="v${{ env.VERSION }}"
          GITHUB_API="https://api.github.com"
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d '{
                  "tag_name": "'"${TAG_NAME}"'",
                  "name": "Release '"${TAG_NAME}"'",
                  "body": "Release notes for version '"${TAG_NAME}"'",
                  "draft": false,
                  "prerelease": false
                }' \
            $GITHUB_API/repos/${{ github.repository }}/releases
            RELEASE_ID=$(echo $response | jq -r .id)

      - name: Upload binary
        run: |
          VSIX_FILE="coding-logs-${{ env.VERSION }}.vsix"
          curl -X PATCH \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @$VSIX_FILE \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID/assets?name=$VSIX_FILE"
